security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    content2: { password: kSqSViZTYC63kTo, roles: [ 'ROLE_ADMIN' ] }
                    content3: { password: W4MZ61g3UN0Jp5f, roles: [ 'ROLE_ADMIN' ] }
                    content4: { password: dW4Gp738Bi7L00J, roles: [ 'ROLE_ADMIN' ] }
                    content5: { password: 80cxC6I2aCV44Cn, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
