index:
    pattern:  /
    defaults: { _controller: EventGeneralBundle:Default:index }

afisha:
    pattern:  /afisha
    defaults: { _controller: EventGeneralBundle:Default:afisha }

search:
    pattern:  /search
    defaults: { _controller: EventGeneralBundle:Default:search }

event:
    pattern:  /events/{year}/{month}/{event_id}
    defaults: { _controller: EventGeneralBundle:Default:event }

profile:
    pattern:  /profile
    defaults: { _controller: EventGeneralBundle:Default:profile }

login_vk:
    pattern:  /login/vk
    defaults: { _controller: EventGeneralBundle:Default:loginVk }

logout:
    pattern:  /logout
    defaults: { _controller: EventGeneralBundle:Default:logout }

subscribe_title:
    pattern:  /user/{uid}/subscribe/title
    defaults: { _controller: EventGeneralBundle:Default:subscribeTitle }

subscribe:
    pattern:  /user/{uid}/subscribe
    defaults: { _controller: EventGeneralBundle:Default:subscribe }

unsubscribe:
    pattern:  /user/{hash}/unsubscribe
    defaults: { _controller: EventGeneralBundle:Default:unsubscribe }

# ADMIN

admin:
    pattern:  /admin
    defaults: { _controller: EventGeneralBundle:Admin:internalEvents }

provider_events:
    pattern:  /admin/events/provider/
    defaults: { _controller: EventGeneralBundle:Admin:providerEvents }

provider_event:
    pattern:  /admin/events/provider/{id}/
    defaults: { _controller: EventGeneralBundle:Admin:providerEvent }

create_internal_event:
    pattern:  /admin/events/internal/create
    defaults: { _controller: EventGeneralBundle:Admin:createInternalEvent }

internal_event:
    pattern:  /admin/events/internal/{id}/
    defaults: { _controller: EventGeneralBundle:Admin:internalEvent }

internal_events:
    pattern:  /admin/events/internal/
    defaults: { _controller: EventGeneralBundle:Admin:internalEvents }

cancel_provider_event:
    pattern:  /admin/events/provider/{id}/cancel
    defaults: { _controller: EventGeneralBundle:Admin:cancelProviderEvent }

matched_provider_event:
    pattern:  /admin/events/provider/{id}/matched
    defaults: { _controller: EventGeneralBundle:Admin:matchedProviderEvent }

unmatch_provider_event:
    pattern:  /admin/events/provider/{id}/unmatch
    defaults: { _controller: EventGeneralBundle:Admin:unmatchProviderEvent }

change_provider_event_place:
    pattern:  /admin/place/{id}/place/change
    defaults: { _controller: EventGeneralBundle:Admin:changeProviderEventPlace }

cancel_internal_event:
    pattern:  /admin/events/internal/{id}/cancel
    defaults: { _controller: EventGeneralBundle:Admin:cancelInternalEvent }

work_internal_event:
    pattern:  /admin/events/internal/{id}/work
    defaults: { _controller: EventGeneralBundle:Admin:workInternalEvent }

work_all_internal_events:
    pattern:  /admin/events/internal/work/all
    defaults: { _controller: EventGeneralBundle:Admin:workAllInternalEvents }

wait_internal_event:
    pattern:  /admin/events/internal/{id}/wait
    defaults: { _controller: EventGeneralBundle:Admin:waitInternalEvent }

add_artist_to_internal:
    pattern:  /admin/events/internal/{id}/artist/add
    defaults: { _controller: EventGeneralBundle:Admin:addArtistToInternal }

drop_artist_from_internal:
    pattern:  /admin/events/internal/{id}/artist/drop
    defaults: { _controller: EventGeneralBundle:Admin:dropArtistFromInternal }

change_match_status:
    pattern:  /admin/events/match/{id}/status/change/{status}/
    defaults: { _controller: EventGeneralBundle:Admin:changeMatchStatus }

places:
    pattern:  /admin/places
    defaults: { _controller: EventGeneralBundle:Admin:places }

create_place:
    pattern:  /admin/place/create
    defaults: { _controller: EventGeneralBundle:Admin:createPlace }

place:
    pattern:  /admin/place/{id}/
    defaults: { _controller: EventGeneralBundle:Admin:place }

change_place_status:
    pattern:  /admin/place/{id}/status/change/{status}/
    defaults: { _controller: EventGeneralBundle:Admin:changePlaceStatus }

matches:
    pattern:  /admin/matches
    defaults: { _controller: EventGeneralBundle:Admin:matches }

change_ticket_status:
    pattern:  /admin/ticket/{id}/status/change/{status}/
    defaults: { _controller: EventGeneralBundle:Admin:changeTicketStatus }

artists:
    pattern:  /admin/artists
    defaults: { _controller: EventGeneralBundle:Admin:artists }

add_artist:
    pattern:  /admin/artist/add
    defaults: { _controller: EventGeneralBundle:Admin:addArtist }

genres:
    pattern:  /genres
    defaults: { _controller: EventGeneralBundle:Admin:genres }

artist:
    pattern:  /artist/{id}/
    defaults: { _controller: EventGeneralBundle:Admin:artist }

search_artists:
    pattern:  /artists/search
    defaults: { _controller: EventGeneralBundle:Admin:searchArtists }

crop_image:
    pattern:  /admin/image/crop
    defaults: { _controller: EventGeneralBundle:Admin:cropImage }

admin_subscribe:
    pattern:  /admin/subscribe
    defaults: { _controller: EventGeneralBundle:Admin:subscribe }

change_subscribe_status:
    pattern:  /admin/subscribe/status
    defaults: { _controller: EventGeneralBundle:Admin:changeSubscribeStatus }

# API ADMIN
match_event:
    pattern:  /api/events/provider/{id}/match
    defaults: { _controller: EventGeneralBundle:Admin:matchEvent }

suggest_mbid:
    pattern:  /api/artist/{id}/mbid/suggest
    defaults: { _controller: EventGeneralBundle:Admin:suggestMbid }

suggest_tags:
    pattern:  /api/artist/{id}/tags/suggest
    defaults: { _controller: EventGeneralBundle:Admin:suggestTags }

# API PUBLIC
personal_afisha:
    pattern:  /api/user/afisha/personal
    defaults: { _controller: EventGeneralBundle:Default:getPersonalAfisha }

sync_status:
    pattern:  /api/user/sync/status
    defaults: { _controller: EventGeneralBundle:Default:syncStatus }

set_tag:
    pattern:  /api/user/tag/set
    defaults: { _controller: EventGeneralBundle:Default:setTag }

get_general_events:
    pattern:  /api/events/general
    defaults: { _controller: EventGeneralBundle:Default:getGeneralEvents }

get_afisha_events:
    pattern:  /api/events/afisha
    defaults: { _controller: EventGeneralBundle:Default:getAfishaEvents }

search_autocomplete:
    pattern:  /api/events/search/autocomplete
    defaults: { _controller: EventGeneralBundle:Default:searchAutocomplete }

get_search_results:
    pattern:  /api/events/search
    defaults: { _controller: EventGeneralBundle:Default:getSearchResults }

like_event:
    pattern:  /api/user/event/like
    defaults: { _controller: EventGeneralBundle:Default:likeEvent }

updateUserEmail:
    pattern:  /api/user/email/update
    defaults: { _controller: EventGeneralBundle:Default:updateUserEmail }

updateUserSettings:
    pattern:  /api/user/settings/update
    defaults: { _controller: EventGeneralBundle:Default:updateUserSettings }

