Event\GeneralBundle\Entity\ActualInternalIndex:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        internal_id:
            type: integer
        name:
            type: string
            length: 255
        urlName:
            type: string
            length: 255
            column: url_name 
            nullable: true
        artists:
            type: text
        tags:
            type: text
            nullable: true
        artistsTags:
            type: text
            column: artists_tags
            nullable: true
        tagsNames:
            type: string
            length: 255
            column: tags_names 
            nullable: true
        catalogRate:
            type: integer
            column: catalog_rate 
            nullable: true
        start:
            type: datetime
        place:
            type: text 
        tickets:
            type: text 
            nullable: true
    lifecycleCallbacks: {  }
