Event\GeneralBundle\Entity\Artist:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        keywords:
            type: text
            nullable: true
        description:
            type: text
            nullable: true
        mbid:
            type: string
            length: 255
            nullable: true
        tags:
            type: text
        urlName:
            type: string
            length: 255
            column: url_name 
            nullable: true
    lifecycleCallbacks: {  }
