Event\GeneralBundle\Entity\InternalEvent:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        date:
            type: date
        start:
            type: datetime
        duration:
            type: integer
        description:
            type: text
            nullable: true
        status:
            type: integer
        place:
            type: integer
        artists:
            type: string
            length: 255
            nullable: true
        tags:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
