Event\GeneralBundle\Entity\InternalEvent:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        urlName:
            type: string
            length: 255
            column: url_name 
        date:
            type: date
        start:
            type: datetime
        duration:
            type: integer
        description:
            type: text
            nullable: true
        status:
            type: integer
        place:
            type: integer
        artists:
            type: string
            length: 255
            nullable: true
        tags:
            type: string
            length: 255
            nullable: true
        catalogRate:
            type: integer
            nullable: true
            column: catalog_rate
        additionalInfo:
            type: text 
            nullable: true
            column: additional_info 
        style:
            type: integer
            nullable: true
        theme:
            type: integer
            nullable: true
        bigTheme:
            type: integer
            nullable: true
            column: big_theme 
        video:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: 
        prePersist: [ processPrePersist ]
        postPersist: [ processPostPersist ]
        preUpdate: [ processPreUpdate ]
        postUpdate: [ processPostUpdate ]
