Event\GeneralBundle\Entity\Tag:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        englishName:
            type: string
            length: 255
            nullable: true
            column: english_name
    lifecycleCallbacks: {  }
