Event\GeneralBundle\Entity\Ticket:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        providerEvent:
            type: integer
            column: provider_event
        sector:
            type: string
            length: 255
        priceMin:
            type: integer
            column: price_min
        priceMax:
            type: integer
            column: price_max
        status:
            type: integer
        secret:
            type: string
            length: 255
        createdAt:
            type: datetime
            column: created_at
    lifecycleCallbacks: 
        prePersist: [ processPrePersist ]
        postPersist: [ processPostPersist ]
        preUpdate: [ processPreUpdate ]
        postUpdate: [ processPostUpdate ]
    uniqueConstraints:
        secret_idx:
            columns: secret 
    indexes:
        provider_idx:
            columns: provider_event
